# Generated by Django 2.0.4 on 2018-04-29 13:27

import accounts.models
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=128, verbose_name='Nome')),
                ('cnpj', models.CharField(error_messages={'invalid': 'O CNPJ deve ter 14 numeros e ser válido.'}, help_text='O CNPJ deve ter 14 numeros e ser válido.', max_length=14, unique=True, validators=[accounts.models.validate_br_cnpj], verbose_name='CNPJ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Usuario ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Criado em')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
