# Generated by Django 2.0.4 on 2018-04-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='ID do Usuário')),
                ('paying_name', models.CharField(max_length=128, verbose_name='Nome do Pagador')),
                ('paying_bank', models.CharField(max_length=3, verbose_name='Banco do Pagador')),
                ('paying_agency', models.CharField(max_length=4, verbose_name='Agência do Pagador')),
                ('paying_account', models.CharField(max_length=6, verbose_name='Conta do Pagador')),
                ('beneficiary_name', models.CharField(max_length=128, verbose_name='Nome do Beneficiário')),
                ('beneficiary_bank', models.CharField(max_length=3, verbose_name='Banco do Beneficiário')),
                ('beneficiary_agency', models.CharField(max_length=4, verbose_name='Agência do Beneficiário')),
                ('beneficiary_account', models.CharField(max_length=6, verbose_name='Conta do Beneficiário')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('type', models.CharField(choices=[('CC', 'Conta Corrente'), ('TED', 'Transfêrencia Eletrônica de Documentos'), ('DOC', 'Documento de Ordem de Crédito')], max_length=4, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('OK', 'OK'), ('ERROR', 'Erro')], max_length=12, verbose_name='Status')),
            ],
        ),
    ]
