# Generated by Django 2.0.4 on 2018-05-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_auto_20180501_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='deleted_at',
            field=models.DateTimeField(null=True, verbose_name='Deletado em'),
        ),
    ]
